webapp/askalma/urls.py
from django.conf.urls import url
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from . import views


app_name = 'askalma'

urlpatterns = [
url(r'^$', views.index, name='index'),
url(r'^index$', views.index, name='index'),
url(r'^search', views.search, name='search'),
url(r'^interest', views.interest, name='interest'),
url(r'^listing', views.listing, name='listing'),
url(r'^post-question', views.postquestion, name='post_question'),
url(r'^profile/$', views.profile, name='profile'),
url(r'^editprofile/$', views.edit_profile ,name='edit_profile'),
url(r'^logout/$', views.logout ,name='logout'),
url(r'^contactus/$' , views.contactus , name="contactus"),
url(r'^question-detail/(?P<qid>([a-zA-Z0-9])*)/$' , views.qdetail , name="q_detail"),
url(r'^iindex$' , views.iindex , name="iindex"),
url(r'^submit_answer$' , views.submit_answer , name='submit_answer')
]

webapp/webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('askalma.urls')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

webapp/askalma/models.py
# from __future__ import unicode_literals
#
# from django.db import models
# from django.core.urlresolvers import reverse
#
# class User (models.Model):
#       email = models.CharField(max_length=64)
#       username = models.CharField(max_length=32)
#     firstname = models.CharField(max_length=64)
#     lastname = models.CharField(max_length=64)

#     def __str__(self):
#         return self.firstname + " " + self.lastname

#     def get_absolute_url (self):
#         return reverse("askalma:qdetail" , kwargs={'pk':self.pk} )

webapp/askalma/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.views import generic
from django.template import RequestContext
from django.urls import reverse
from django.shortcuts import redirect
from .models import *
from django.shortcuts import render
import time
from django.views.decorators.csrf import csrf_exempt
from elasticsearch import Elasticsearch
from urlparse import urlparse
import gdata.client
import gdata.gauth
import json
from wordVectorClassifier import machineLearning
import gdata.photos.service #In this example where contacting Google Picasa Web API
from gensim.models import word2vec
import watson_developer_cloud
import watson_developer_cloud.natural_language_understanding.features.v1 as features
nlu = watson_developer_cloud.NaturalLanguageUnderstandingV1(version='2017-05-11',
                                                            username='92475337-a51a-47f2-b42e-69e772b1e3cc',
                                                            password='NdHjAGCYDeOf')

es = Elasticsearch("search-askalma-ec4hakudbwu54iw5gnp6k6ggpy.us-east-1.es.amazonaws.com", port=443,
				   use_ssl='true')


def _isLoggedIn(request):
	try:
		email = request.session['email']
		last_in = request.session['last_in']
		#Thirty minute old sessions are killed
		if (time.time()- last_in > 1800):
			return HttpResponseRedirect(reverse('social:begin' ,args=('google-oauth2',)))
		request.session['last_in'] = time.time()
		return None
	except KeyError:
		return HttpResponseRedirect(reverse('social:begin' ,args=('google-oauth2',)))

@csrf_exempt
def index(request):
	#Add these two lines to any page that requires user to be logged in
	result = _isLoggedIn(request)
	if result != None: return result
	result= getquestions(request)
	context = {}
	context['stats'] = _getStats()
	#if result.get('question')!="nothing":
	#	return result
	return render(request, 'askalma/index.html', context=context)

def search(request):
	result = _isLoggedIn(request)
	if result != None: return result
	response= getquestions(request)
	print(response)
	return render(request, 'askalma/listing.html'  , context = response)

# def search(request):
# 	context = {}
# 	response = getquestions(request)
# 	if response.get('questions') == "": return render(request, 'askalma/index.html', context=context)
# 	return response
# 	#return render(request, 'askalma/listing.html' , context = context)

def getquestions(request):
	searchstring= str(request.GET.get('querystring', ' '))
	print searchstring
	try:
		result=es.search(index='questions1', body={"from" : 0, "size" : 1000, "query":{ "query_string": { "query": searchstring, "default_field": 'title' }}})
		result=result['hits']['hits']
		print result
		b=[]
		for q in result:
			tags= q['_source']['tags']
			taglist= [s.strip() for s in tags.split(',')]
			a = {
			"title": q['_source']['title'],
			"taglist": taglist,
			"details": q['_source']["details"]
			}
			b.append(a)
			print(b)
		return {'questions': b }
	except KeyError:
		return {'questions': "nothing"}

def listing(request):
	result = _isLoggedIn(request)
	if result != None: return result
	response = searchquestion(request)
	print(response)
	return render(request, 'askalma/listing.html'  , context = response)

def searchquestion(request):
    try:
        result=es.search(index='questions1', body={"from" : 0, "size" : 1000, "query":{"match_all": {}}})
        print result
        questions= result['hits']['hits']
		#print questions
        b= []
        for question in questions:
            tags= question['_source']['tags']
            taglist= [s.strip() for s in tags.split(',')]
            sentimentOutput = nlu.analyze(text=question['_source']['title'], features=[features.Sentiment()])
            sentiment = sentimentOutput['sentiment']['document']['label']
            a = {
			"title": question['_source']['title'],
			"taglist": taglist,
			"details": question['_source']["details"],
			"qid" : question['_id'],
            "sentiment": sentiment
			}
            b.append(a)
        print b
        return {'questions': b }
    except KeyError:
		return {'questions': "nothing"}

@csrf_exempt
def postquestion(request):
	result = pullquestion(request)
	if result== "data":
		return render(request, 'askalma/listing.html')
	else:
		return render(request, 'askalma/post-question.html')

def pullquestion(request):
	try:
		#print "sending question to elasticsearch"
		title= str(request.GET.get("title", ' '))
		#print title
		tags= str(request.GET.get("tags", ' '))
		#print tags
		details= str(request.GET.get("details", ' '))

		# Add tags like tags = tags + ", " + "Columbia"
		if title != " ":
			categoryOutput = nlu.analyze(text=title, features=[features.Categories()])
			if len(categoryOutput['categories']) != 0:
				if tags != "":
					tags = tags + ", " + categoryOutput['categories'][0]['label']
				else:
					tags = categoryOutput['categories'][0]['label']
			keywordOutput = nlu.analyze(text=title, features=[features.Keywords()])
			if len(keywordOutput['keywords']) != 0:
				tags = tags + ", " + keywordOutput['keywords'][0]['text']
			conceptOutput = nlu.analyze(text=title, features=[features.Concepts()])
			if len(conceptOutput['concepts']) != 0:
				tags = tags + ", " + conceptOutput['concepts'][0]['text']

		#print details
		#print "inside es working"
		user_profile =_get_user_profile (request.session['email'])
		user_email= user_profile[0].get('email')
		user= es.search(index='users', body={"from" : 0, "size": 1000, "query":{ "query_string": {"query": user_email, "default_field": "email"}}})["hits"]["hits"]
		for u in user:
			user_id= u.get("_id")
			es.update(index= 'users', doc_type="user", id= user_id, body= {"doc": {"user_questions": " "+title}})
		doc = {
			"title": title,
			"tags": tags,
			"details": details,
			"user_id":user_id
		}
		if title!=" ":
			es.index(index="questions1", doc_type='question', body=doc)
			print doc
		return HttpResponseRedirect("data")
	except KeyError:
		return HttpResponseRedirect("webpage")

def profile(request):
	result = _isLoggedIn(request)
	if result != None: return result
	#print user_info
	#print context
	user_info, x =_get_user_profile (request.session['email'])
	context = {'user_info' : user_info}
	return render(request , 'askalma/profile-setting.html', context= context)

def edit_profile (request ):
	result = _isLoggedIn(request)
	if result != None: return result

	user_info, x =_get_user_profile (request.session['email'])
	context = {'user_info' : user_info}
	return render(request , 'askalma/profile-setting.html', context= context)

def logout(request):
	try:
		del request.session['email']
	except:
		pass
	return index(request)

def contactus (request):
	pass

@csrf_exempt
def qdetail(request, qid):
	# ADD LOGIN
	context = _get_question_details (qid)
	print context
	return render(request, 'askalma/question_detail.html' , context = context)


def _get_question_details( qid):
	query = es.get(index="questions1", doc_type='question' , id=qid)
	question = query ['_source']
	question['id']  = query['_id']
	tags= question['tags']
	taglist= [s.strip() for s in tags.split(',')]
	print taglist
	print "first tag"
	print taglist[0]
	print "second tag"
	#answers = es.search ("doc is query for questions = qid ")
	answers= es.search(index='answers3', body={"from" : 0, "size" : 1000,"query":{ "query_string": { "query": question['id'] , "default_field": 'question_id' }}})
	print answers
	answers=answers['hits']['hits']
	b=[]
	for answer in answers:
		source = answer.get('_source')
		a={}
		a['answer_text'] = source.get('answer_text')
		a['user_id'] = source.get('user_id')
		users= es.search(index= 'users',body={"from" : 0, "size" : 1000,"query":{"match_all": {}}})["hits"]["hits"]
		#result=es.search(index='questions1', body={"from" : 0, "size" : 1000, "query":{"match_all": {}}})
		print "This are users"
		print users
		for user in users:
			id= user.get('_id')
			if a['user_id']==id:
				source1 = user.get('_source')
				a['firstname']= source1.get('firstname')
				a['lastname']= source1.get('lastname')
		b.append(a)
	print ("This are the answers and users")
	print b
	#answers = None
	return {'question' : question , 'answers' : b, 'taglist': taglist}

#JUST UNCOMMENT the two lines
def _getStats ():
	stats = {}
	stats['views'] = 7812
	stats['questions'] = es.search(index='questions1', body={"size": 0,})['hits']['total']
	stats['answersed_questions'] = es.search(index='questions1', body={"size": 0,"query":{ "query_string": { "query": 1, "default_field": 'answered' }}})['hits']['total']
	stats['users'] =  es.search(index='users', body={"size": 0,})['hits']['total']
	stats['answered_questions'] = 24

	return stats

def iindex(request):
	#While this should an error page, it seems that it is nothing too serious, just redirect to index
	return index(request)


def process_auth(details,strategy,request,**kwargs):
	#Add user info to session, to keep them logged in
	strategy.session_set('email', details['email'])
	strategy.session_set('last_in', time.time())
	strategy.session_set('first_name', details['first_name'])
	strategy.session_set('last_name', details['last_name'])
	strategy.session_set('last_name', details['last_name'])
	#Check if they exist in ES. IF not, add them.
	count = es.search(index='users', body={"size": 0,"query":{ "query_string": { "query": details['email'] , "default_field": 'email' }}})['hits']['total']
	if count == 0:
		doc = {
			"email": details['email'],
			"last_name": details['last_name'],
			"headline" : "Student at Columbia University",
			"profile_pic" : "default.jpg"
		}
		es.index(index="users", doc_type='user', body=doc)

def _get_user_profile (email):
	res = es.search(index='users', body={"from": 0, "size": 1, "query": {
		"query_string": {"query": email, "default_field": 'email'}}})
	return res['hits']['hits'][0]['_source'], res['hits']['hits'][0]['_id']

def interest(request):
	result = _isLoggedIn(request)
	if result != None: return result
	response= getinterests(request)

webapp/askalma/templates/askalma/post-question.html
{% extends 'askalma/headerfooter.html' %}
{% block title %}Post A Question - AskAlma{% endblock %}
{% load staticfiles %}

{% block body %}
    <!-- =-=-=-=-=-=-= Post Question  =-=-=-=-=-=-= -->
  <html>
    <section class="section-padding-80 white" id="post-question">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-8 ">

            <div class="box-panel">

              <h2>Post Your Question</h2>
              <hr>
              <!-- form login -->
              <form class="margin-top-40">
                <div class="form-group">
                  <label>Question Title</label>
                  <input type="text" placeholder="Enter question title..." class="form-control" id= "title">
                </div>
                <div class="form-group">
                  <label>Tags</label>

                  <input type="text" id="tags" value="" class="form-control" data-role="tagsinput">
                </div>

                <div class="form-group">
                  <label>Question Details</label>
                  <textarea cols="12" rows="12" placeholder="Post Your Question Details Here....." id="details" name="message" class="form-control"></textarea>
                </div>

                <button class="btn btn-primary pull-right" onclick="collect()" name= "action" value= "Senddata">Publish Your Question</button>
              </form>
              <!-- form login -->

            </div>
          </div>

          <!-- Blog Right Sidebar -->
          <div class="col-sm-12 col-xs-12 col-md-4">

            <!-- sidebar -->
            <div class="side-bar">

              <!-- widget -->
              <div class="widget">
                <div class="recent-comments">
                  <h2>Hot Questions</h2>
                  <hr class="widget-separator no-margin">
                  <ul>
                    <li><a href="#">Who is the most popular celebrity on Columbia's campus?</a>
                    </li>
                    <li><a href="#">What is the best dorm to live in at Columbia?</a>
                    </li>
                    <li><a href="#">Where can I make money off campus? </a>
                    </li>
                    <li><a href="#">Where are the best parties on campus? </a>
                    </li>

                    <li><a href="#">post data from html form to php script and return result to ajax/js/jquery </a>
                    </li>
                  </ul>
                </div>
              </div>
              <!-- widget -->

              <!-- widget -->
              <!-- widget end -->

            </div>
            <!-- sidebar end -->

          </div>
          <!-- Blog Right Sidebar End -->
          <div class="clearfix"></div>
        </div>
      </div>
      <!-- end container -->
    </section>
    <!-- =-=-=-=-=-=-= Post QuestionEnd =-=-=-=-=-=-= -->



  </div>
  <script type= "text/javascript">
    function collect()
    {
      var title= document.getElementById("title").value;
      var tags= document.getElementById("tags").value;
      var details= document.getElementById("details").value;
      $.ajax({ // use ajax to pass the obtained value from searchbox
      url : "/post-question/",
      method : "GET",
      dataType: "json",
      data: {
      title: title,
      tags: tags,
      details: details
      },
      success: function (result)
      {
        if (result== "sucess")
        {
          windows.location.href= "listing.html";
        }
        else
        {
        windows.location.href= "post-question.html";
        }
      },
      error: function (textStatus, errorThrown)
      {
        console.log("Text status "+textStatus+" Error is "+errorThrown);
      }
      });
    }
</script>
</html>
  <!-- =-=-=-=-=-=-= Main Area End =-=-=-=-=-=-= -->
{% endblock %}

webapp/askalma/templates/askalma/question_detail.html
{% extends 'askalma/headerfooter.html' %}
{% block title %}Profile - AskAlma{% endblock %}
{% load staticfiles %}

{% block body %}

<!-- =-=-=-=-=-=-= Question Details =-=-=-=-=-=-= -->

    <section class="section-padding-80 white question-details">
      <div class="container">
        <!-- Row -->
        <div class="row">
          <div class="col-md-8 col-lg-8 col-sm-12 col-xs-12">
            <!-- Question Detail -->

            <!-- Question Listing -->
            <div class="listing-grid ">
              <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div id="title" method="get">
                  <h3><a  href="/question-detail/{{ question.qid }}"> {{ question.title }} </a></h3>
                  </div>
<!--                  <div class="listing-meta"> <span><i class="fa fa-clock-o" aria-hidden="true"></i>8 mintes ago</span> <span><i class="fa fa fa-eye" aria-hidden="true"></i> 750 Views</span> </div> -->                  <div id= "details" >
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <p > <a href="/question-detail/{{ question.qid }}">
                     {{ question.details }} </a> </p>
                </div>

                </div>
                {% for tag in taglist%}
                  <div class="tagcloud"> <a href="/question-detail/{{ question.qid }}" id="t1">{{tag}}</a> <!--<a href="" id="t2">tag[1]</a> <a href="" id="t3">bootstrap</a>--> </div>
                  {% endfor %}
                </div>
              </div>
            </div>
            <!-- Question Listing End -->

            <div class="clearfix"></div>
            <!-- Thread Reply -->
            <div class="thread-reply">

              <h2>Thread Reply </h2>
                                {% for answer in answers %}
              <!-- Reply Grid -->

              <div class="media-block card-box ribbon-content">
                <div class="media-body">
                  <div class="mar-btm">
                    <h4><a href="#" class="btn-link text-semibold media-heading box-inline">Anonymous</a></h4>
                    <!-- <p class="text-muted text-sm"><i class="fa fa-mobile fa-lg"></i> - From Mobile - 11 min ago</p> -->
                  </div>

                  <p>
                    <!--I think this is what you are looking for. You need to remove the <code>float: left</code> from the inner nav to center it and make it a inline-block.</p>
                  <pre class="brush: php syntaxhighlight">
                        .navbar .navbar-nav {
                          display: inline-block;
                          float: none;
                          vertical-align: top;
                        }

                        .navbar .navbar-collapse {
                          text-align: center;
                        }
                                </pre>
                  <p><strong>Edit: </strong>if you only want this effect to happen when the nav isn't collapsed surround it in the appropriate media query.</p>
                  <pre class="brush: php syntaxhighlight">
                        @media (min-width: 768px) {
                            .navbar .navbar-nav {
                                display: inline-block;
                                float: none;
                                vertical-align: top;
                            }

                            .navbar .navbar-collapse {
                                text-align: center;
                            }
                        }
                      </pre> -->
                      {{answer.answer_text}}
<!--                  <div class="pad-ver pull-right">

                    <a class="btn btn-sm btn-default btn-hover-success" data-toggle="tooltip" data-placement="bottom" data-original-title="Like This Answer" href="#"><i class="fa fa-thumbs-up"></i></a>
                    <a class="btn btn-sm btn-default btn-hover-danger" href="#" data-original-title="Spam" data-placement="bottom" data-toggle="tooltip"><i class="fa fa-thumbs-down"></i></a>

                  </div>

                </div>
              </div> -->
              <!-- Reply Grid End -->
              <!-- Reply Grid -->
        <!--      <div class="media-block card-box ">

                <div class="media-left">
                  <a href="#">
                    <img class="img-sm" alt="Profile Picture" src="images/authors/7.jpg">

                  </a>

                </div>
                <div class="media-body">
                  <div class="mar-btm">
                    <h4><a href="#" class="btn-link text-semibold media-heading box-inline">Martina Jaz</a></h4>
                    <p class="text-muted text-sm"><i class="fa fa-mobile fa-lg"></i> - From Mobile - 21 min ago</p>
                  </div>
                  <p>I think this is what you are looking for. You need to remove the <code>float: left</code> from the inner nav to center it and make it a inline-block.</p>
                  <pre class="brush: php syntaxhighlight">
$('#nav').affix({
      offset: {
        top: $('header').height()
      }
});
                                </pre>
                  <div class="pad-ver pull-right">

                    <a class="btn btn-sm btn-default btn-hover-success" data-toggle="tooltip" data-placement="bottom" data-original-title="Like This Answer" href="#"><i class="fa fa-thumbs-up"></i></a>
                    <a class="btn btn-sm btn-default btn-hover-danger" href="#" data-original-title="Spam" data-placement="bottom" data-toggle="tooltip"><i class="fa fa-thumbs-down"></i></a>

                    <a class="btn btn-sm btn-default btn-hover-primary" href="#">Mark As Correct</a>
                  </div>
-->
                </div>
              </div>
              <!-- Reply Grid End -->
              <!-- Reply Grid -->
<!--              <div class="media-block card-box ">

                <div class="media-left">
                  <a href="#">
                    <img class="img-sm" alt="Profile Picture" src="images/authors/6.jpg">

                  </a>

                </div>
                <div class="media-body">
                  <div class="mar-btm">
                    <h4><a href="#" class="btn-link text-semibold media-heading box-inline">John Doe</a></h4>
                    <p class="text-muted text-sm"><i class="fa fa-mobile fa-lg"></i> - From Mobile - 40 min ago</p>
                  </div>
                  <p>I think this is what you are looking for. You need to remove the <code>float: left</code> from the inner nav to center it and make it a inline-block.</p>
                  <pre class="brush: php syntaxhighlight">
$(function(){
    $('.block').affix();
})
                                </pre>
                  <div class="pad-ver pull-right">

                    <a class="btn btn-sm btn-default btn-hover-success" data-toggle="tooltip" data-placement="bottom" data-original-title="Like This Answer" href="#"><i class="fa fa-thumbs-up"></i></a>
                    <a class="btn btn-sm btn-default btn-hover-danger" href="#" data-original-title="Spam" data-placement="bottom" data-toggle="tooltip"><i class="fa fa-thumbs-down"></i></a>

                    <a class="btn btn-sm btn-default btn-hover-primary" href="#">Mark As Correct</a>
                  </div>

                </div>
              </div>
            -->
              {% endfor %}
              <!-- Reply Grid End -->

              <div class="clearfix"></div>

              <form method="post" action="{% url 'askalma:submit_answer' %}">
                <div class="form-group">
                  <label>Post Your Answer</label>
                    <input type="hidden" name="qid" value="{{ question.id }}">
                  <textarea cols="12" rows="7" class="form-control" placeholder="I Have The Answer" name= "answer"></textarea>
                </div>

                <button class="btn btn-primary btn-lg btn-block" id= "answer_button" type="submit">Post Your Answer</button>

              </form>

            </div>
            <!-- Thread Reply End -->
          </div>

          <!-- Right Sidebar -->
          <!--
          <div class="col-md-4 col-sm-12 col-xs-12 clearfix"> -->

            <!-- sidebar -->
            <!--
            <div class="side-bar">
              <div class="widget">
                <div class="widget-image widget-image-sm"> <img alt="image" src="images/light-background.jpg">
                  <div class="widget-image-content text-center"> <img class="img-thumbnail" alt="avatar" src="images/authors/12.jpg">
                    <h2 class="widget-heading text-light"><strong>John Doe</strong></h2>
                    <h4 class="widget-heading text-light-op"><em>Computer Science Junior</em></h4>
                  </div>
                </div>
                <div class="widget-content widget-content-full border-bottom">
                  <div class="row text-center">
                    <div class="col-xs-6 push-inner-top-bottom border-right">
                      <h3 class="widget-heading"><i class=" icon-trophy push"></i> <br>
                                            <small><strong>34</strong> Questions</small></h3>
                    </div>
                    <div class="col-xs-6 push-inner-top-bottom">
                      <h3 class="widget-heading"><i class=" icon-profile-male themed-color-social push"></i> <br>
                                            <small><strong>58</strong> Answers</small></h3>
                    </div>
                  </div>
                </div>
                <div class="widget-content border-bottom">
                  <h4>About</h4>
                  <p>Proin ac nibh rutrum lectus rhoncus eleifend. Sed porttitor pretium venenatis. Suspendisse potenti. Aliquam quis ligula elit.</p>
                  <p>Sed porttitor pretium venenatis. Suspendisse potenti. Aliquam quis ligula elit. Aliquam at orci ac neque semper dictum.</p>
                </div>
              </div>



            </div>
            <!-- sidebar end -->
          </div>
        -->
          <!-- Right Sidebar End -->

        </div>
        <!-- Row End -->
      </div>
    </section>
    <!-- =-=-=-=-=-=-= Question Details end =-=-=-=-=-=-= -->
  </div>
  <!-- =-=-=-=-=-=-= Main Area End =-=-=-=-=-=-= -->
  <script type="text/javascript">
  function submitf()
  {
    var ans= document.getElementById("answer_text").value;
    var question= document.getElementById("title").value;
      $.ajax({ // use ajax to pass the obtained value from searchbox
    url : "/question-detail/",
    method : "GET",
    dataType: "json",
    data: {
    answer_text :ans,
    question_text:question
    },
    success: function (result)
    {
      if (result== "sucess")
      {
        windows.location.href= "listing.html";
      }
      else
      {
        windows.location.href= "question-detail.html";
      }
    },
    error: function (textStatus, errorThrown)
    
      console.log("Text status "+textStatus+" Error is "+errorThrown);
    }
    });
  }
</script>
{%  endblock %}